"""Create initial tables

Revision ID: 2f64de060dd9
Revises: 
Create Date: 2026-05-31 21:56:22.467600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f64de060dd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('crop_name_en', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('crop_id'),
    sa.UniqueConstraint('crop_name')
    )
    op.create_index(op.f('ix_crop_crop_id'), 'crop', ['crop_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False, server_default='user'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('disease',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('disease_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.crop_id'], ),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_index(op.f('ix_disease_disease_id'), 'disease', ['disease_id'], unique=False)
    op.create_table('pests',
    sa.Column('pest_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('pest_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.crop_id'], ),
    sa.PrimaryKeyConstraint('pest_id')
    )
    op.create_index(op.f('ix_pests_pest_id'), 'pests', ['pest_id'], unique=False)
    op.create_table('user_one_time_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_one_time_tokens_id'), 'user_one_time_tokens', ['id'], unique=False)
    op.create_table('plant_diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('pest_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('user_corrected_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.crop_id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['pest_id'], ['pests.pest_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_diary_id'), 'plant_diary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_diary_id'), table_name='plant_diary')
    op.drop_table('plant_diary')
    op.drop_index(op.f('ix_user_one_time_tokens_id'), table_name='user_one_time_tokens')
    op.drop_table('user_one_time_tokens')
    op.drop_index(op.f('ix_pests_pest_id'), table_name='pests')
    op.drop_table('pests')
    op.drop_index(op.f('ix_disease_disease_id'), table_name='disease')
    op.drop_table('disease')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_crop_crop_id'), table_name='crop')
    op.drop_table('crop')
    # ### end Alembic commands ###