"""initial_migration

Revision ID: 31400db5ce39
Revises: 
Create Date: 2026-04-11 23:57:25.595717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31400db5ce39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crop', 'crop_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_crop_crop_id'), 'crop', ['crop_id'], unique=False)
    op.create_unique_constraint(None, 'crop', ['crop_name'])
    op.alter_column('disease', 'disease_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('disease', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('disease', 'treatment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_disease_disease_id'), 'disease', ['disease_id'], unique=False)
    op.alter_column('pests', 'crop_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pests', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('pests', 'treatment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_pests_pest_id'), 'pests', ['pest_id'], unique=False)
    op.alter_column('plant_diary', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('plant_diary', 'crop_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('plant_diary', 'image_url',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('plant_diary', 'confidence',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('plant_diary', 'suggestion',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('plant_diary', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_plant_diary_id'), 'plant_diary', ['id'], unique=False)
    op.create_foreign_key(None, 'plant_diary', 'crop', ['crop_id'], ['crop_id'])
    op.create_foreign_key(None, 'plant_diary', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'plant_diary', 'disease', ['disease_id'], ['disease_id'])
    op.create_foreign_key(None, 'plant_diary', 'pests', ['pest_id'], ['pest_id'])
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'"))
    op.drop_constraint(None, 'plant_diary', type_='foreignkey')
    op.drop_constraint(None, 'plant_diary', type_='foreignkey')
    op.drop_constraint(None, 'plant_diary', type_='foreignkey')
    op.drop_constraint(None, 'plant_diary', type_='foreignkey')
    op.drop_index(op.f('ix_plant_diary_id'), table_name='plant_diary')
    op.alter_column('plant_diary', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('plant_diary', 'suggestion',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('plant_diary', 'confidence',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('plant_diary', 'image_url',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)
    op.alter_column('plant_diary', 'crop_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('plant_diary', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_pests_pest_id'), table_name='pests')
    op.alter_column('pests', 'treatment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pests', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('pests', 'crop_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_disease_disease_id'), table_name='disease')
    op.alter_column('disease', 'treatment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('disease', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('disease', 'disease_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'crop', type_='unique')
    op.drop_index(op.f('ix_crop_crop_id'), table_name='crop')
    op.alter_column('crop', 'crop_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
