"""update disease and pest

Revision ID: 6cddf6c41ab7
Revises: c503f6c775cd
Create Date: 2026-05-19 01:39:17.581076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cddf6c41ab7'
down_revision: Union[str, Sequence[str], None] = 'c503f6c775cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_user_one_time_tokens_user_purpose'), table_name='user_one_time_tokens')
    #op.drop_index(op.f('uq_user_one_time_tokens_token_hash'), table_name='user_one_time_tokens')
    #op.drop_table('user_one_time_tokens')
    op.alter_column(
        'plant_diary',           # 資料表名稱
        'suggestion',            # 欄位名稱
        type_=sa.Text(),         # 關鍵：目標型態改成 Text
        existing_nullable=True   # 是否允許為空值
    )

    # 如果 treatment 欄位也要改，就再加一行：
    op.alter_column(
        'plant_diary',
        'treatment',
        type_=sa.Text(),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_one_time_tokens',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purpose', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('token_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_user_one_time_tokens_token_hash'), 'user_one_time_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_one_time_tokens_user_purpose'), 'user_one_time_tokens', ['user_id', 'purpose'], unique=False)
    # ### end Alembic commands ###
