"""align database with current models

Revision ID: 8766043b40ed
Revises: 2f64de060dd9
Create Date: 2026-06-03 15:19:03.807018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8766043b40ed'
down_revision: Union[str, Sequence[str], None] = '2f64de060dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE user SET email_verified_at = NOW() WHERE email_verified_at IS NULL")
    op.alter_column('user', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint(op.f('fk_user_tokens_user_id'), 'user_one_time_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_user_one_time_tokens_user_purpose'), table_name='user_one_time_tokens')
    op.create_index(op.f('ix_user_one_time_tokens_id'), 'user_one_time_tokens', ['id'], unique=False)
    op.create_foreign_key(None, 'user_one_time_tokens', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_one_time_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_user_one_time_tokens_id'), table_name='user_one_time_tokens')
    op.create_index(op.f('ix_user_one_time_tokens_user_purpose'), 'user_one_time_tokens', ['user_id', 'purpose'], unique=False)
    op.create_foreign_key(op.f('fk_user_tokens_user_id'), 'user_one_time_tokens', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('user', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###