"""新增欄位

Revision ID: c56b561c634c
Revises: 8bc62f9f90c6
Create Date: 2026-08-30 00:40:05.355515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c56b561c634c'
down_revision: Union[str, Sequence[str], None] = '8bc62f9f90c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnosis_feedback', 'prediction_id',
               existing_type=mysql.VARCHAR(length=64),
               comment='關聯的預測 ID',
               existing_nullable=True)
    op.create_index(op.f('ix_diagnosis_feedback_prediction_id'), 'diagnosis_feedback', ['prediction_id'], unique=False)
    op.drop_column('diagnosis_feedback', 'manager_corrected_disease_name')
    op.drop_column('diagnosis_feedback', 'manager_corrected_plant_name')
    op.alter_column('user', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_verified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('diagnosis_feedback', sa.Column('manager_corrected_plant_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('diagnosis_feedback', sa.Column('manager_corrected_disease_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_diagnosis_feedback_prediction_id'), table_name='diagnosis_feedback')
    op.alter_column('diagnosis_feedback', 'prediction_id',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='關聯的預測 ID',
               existing_nullable=True)
    # ### end Alembic commands ###
