"""Add diagnosis_feedback table

Revision ID: dca0981cea69
Revises: 0ea8fef2d664
Create Date: 2026-06-05 18:24:39.545406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca0981cea69'
down_revision: Union[str, Sequence[str], None] = '0ea8fef2d664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('original_plant_name', sa.String(length=100), nullable=True),
    sa.Column('original_disease_name', sa.String(length=100), nullable=True),
    sa.Column('is_plant_error', sa.Boolean(), nullable=True),
    sa.Column('is_disease_error', sa.Boolean(), nullable=True),
    sa.Column('corrected_plant_name', sa.String(length=100), nullable=True),
    sa.Column('corrected_disease_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_feedback_id'), 'diagnosis_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_feedback_id'), table_name='diagnosis_feedback')
    op.drop_table('diagnosis_feedback')
    # ### end Alembic commands ###
